name: CI/CD Pipeline

# Trigger the workflow on push to the main branch
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Uses the actions/checkout action to clone the repository.
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Print Hello World.
      - name: Hello World
        run: echo "Hello World"

      # This step installs JDK 17 from the Eclipse Temurin distribution in the GitHub Actions environment,
      #  ensuring the specified Java version is available for subsequent workflow step.
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      # Uses the actions/setup-node action to set up the specified Node.js version (e.g., version 21.7.1).
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "21.7.1"

      # Installs the project's dependencies using npm install.
      - name: Install dependencies
        run: npm install

      # Builds the Android application using Gradle.
      - name: Build Android
        run: |
          cd android
          ./gradlew assembleRelease

      # Uses the actions/upload-artifact action to upload the generated APK file as an artifact.
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-release
          path: ./android/app/build/outputs/apk/release/app-release.apk
